tmp

diff --git a/.github/workflows/back-button-check.yml b/.github/workflows/back-button-check.yml
--- a/.github/workflows/back-button-check.yml
+++ b/.github/workflows/back-button-check.yml
@@ -2,14 +2,11 @@ name: Check Back Button
 
 on:
   push:
+    branches:
+      - ft/back-button-check
     paths:
       - "**/*.md"
   pull_request:
-    types:
-      - opened
-      - edited
-      - synchronize
-      - reopened
     paths:
       - "**/*.md"
 
@@ -25,13 +22,14 @@ jobs:
       - name: Verify Markdown Files
         run: |
           echo "Checking markdown files..."
-          # Find all .md files excluding root README.md
-          find . -name "*.md" ! -path "./README.md" | while read file; do
-            # Check the first line of each file
-            first_line=$(head -n 1 "$file")
-            if [[ "$first_line" != "⬅️ [Back to Main Menu](../README.md#contents)" ]]; then
-              echo "❌ Error: $file does not contain the required first line."
-              exit 1
-            fi
+          # Find all .md files excluding root README.md and files in .github/workflows
+          find . -name "*.md" \
+            ! -path "./README.md" | while read file; do
+              # Check the first line of each file
+              first_line=$(head -n 1 "$file")
+              if [[ "$first_line" != "⬅️ [Back to Main Menu](../README.md#contents)" ]]; then
+                echo "❌ Error: $file does not contain the required first line."
+                exit 1
+              fi
           done
           echo "✅ All markdown files contain the required first line."
